### ISSUE TITLE
Improve v2 Logging

### ISSUE THREAD

**Issue by mike-mcgrail** [scalyr/dataset-addon-for-splunk#18]
v2 reverted some logging updates. 

Example of a query that has no results, and instead of a clean logged message results in an error exit:

<img width="617" alt="Screenshot 2023-05-15 at 2 47 36 PM" src="https://github.com/scalyr/dataset-addon-for-splunk/assets/32044603/fe2edd90-78d2-4f0d-84b6-5981cff084d0">

Example of an empty PowerQuery filter:
<img width="408" alt="Screenshot 2023-05-15 at 2 49 35 PM" src="https://github.com/scalyr/dataset-addon-for-splunk/assets/32044603/b984e81c-fe5c-41fc-9a86-f9ad86fef868">

Example of incorrect API token:
<img width="229" alt="Screenshot 2023-06-05 at 10 28 49 AM" src="https://github.com/scalyr/dataset-addon-for-splunk/assets/32044603/69aba49d-9f84-48e7-ad4c-8c5525a273ff">

**Comment by saurabh-dongare-s1** [comment]
Closing this as this is no longer valid - the logging should be clear enough to tell what is wrong now. This was handled quite a few versions back!
